server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.17.5.52;SelectMethod=cursor;DatabaseName=yuetao_rec
    username: xinhua
    password: xinhua2021